### PR TITLE
Support migration

### PR DESCRIPTION
**Pull request by chhsiao1981**
This is the follow-up of #40.

Adding support with migrate-from-file-to-db and migrate-from-db-to-file.

I'll rewrite edit_post as demo for the new storage framework.

### CODE REVIEW

**Comment by wens** [comment]
Please don't put everything in just one or two commits. It is very hard to do any meaningful review.

Consider adding each component one-by-one in separate commits. Ideally the storage layer should be abstracted away from its consumers, such that new installations can simply drop-in whichever backend they like. For example, you can start with an overall design document. Then start introducing abstraction layers (or simply clean up existing interfaces). Then one by one introduce new backends for each data structure in the system.

Data migration is a separate issue.

**Comment by chhsiao1981** [comment]
hi @wens 

I am very sorry for the confusion.

The following doc (in Chinese) intends to explain the design of the new storage framework.

https://docs.google.com/document/d/1Zkd03s3ZFjfibACft4RBB0Dn1dndxJ9uyETY2BIyLyY/edit

I'll try to break down the commits with the following sub-commits:
1. integrate with googletest
2. util-files. (ptterr.h, util_db, pttdb_uuid, pttdb_dict_bson_by_uu, pttdb_util, util_timestamp)
3. main-content-related (pttdb_main, pttdb_content_block)
4. comment-related (pttdb_comment)
5. comment-reply-related (pttdb_comment_reply)
6. migrate-db-to-file-related
7. migrate-file-to-db-related.

**Comment by robertabcd** [comment]
Not having read your design document, I agree with @wens that we need an abstraction layer for storage, and the ability to switch storage backends easily.

**Comment by robertabcd** [comment]
I quickly scanned thorugh your document. It lists some requirements and compromises you want to make; however, it is not a design.

**Comment by chhsiao1981** [comment]
hi @robertabcd,

Thank you so much for the comments～

Maybe what you mean by "system design" is about more detailed design of the data-structure and the corresponding workflow of the ops (CRUD of the post)?

The following docs and slides intend to illustrate the more detailed design:
(And I do need to revise the PR based on the following doc～)

https://docs.google.com/document/d/1AMQSQe4iG7ZMCQNlSD6STglZViIk2s7VNF-l3WhegA4/edit

https://docs.google.com/presentation/d/1yFwPFZN2W7Ygn9CwRfisloS5I7x2mTvrj2iTvjcxa5Y/edit#slide=id.g35f56f51ce_0_5

**Comment by chhsiao1981** [comment]
Based on the previous discussion,
the commits of the code has been refactored as several parts.
And you can see that I've put the new code as modules (common/pttdb, common/migrate_pttdb)
The new refactoring will not interfere with existing code/Makefile at all.

The sketch of the design is also available in the following docs
(Mostly same as previously mentioned)

https://docs.google.com/document/d/1Zkd03s3ZFjfibACft4RBB0Dn1dndxJ9uyETY2BIyLyY/edit
(2018-03-29 ptt refactor design)

https://docs.google.com/document/d/1AMQSQe4iG7ZMCQNlSD6STglZViIk2s7VNF-l3WhegA4/edit
(2018-03-29 ptt refactor design-2)

This PR does not include the UI-part yet～
I'll include the new edit-UI in the next PR.

**Comment by chhsiao1981** [comment]
close this pr for now and I'll have a new WIP pr.

**Pull request closed without merging**
